language: node_js
node_js:
  - "7"
deploy:
  provider: firebase
  token:
    secure: "oL1nDsHyJ7wg9dVuVR+9Pzk6vs82w9wvMNUI6kiQEQzUAfFdpZbBdA1esrru2AFck6WqYvkcyIhW0d0GggqkqynA7KzUtf5U2cHAUTS31nPQYfez84BZwtRrnhhLTBKnuTzu+qXyGSyaptbkAUnvFI1b4uLgOpSA13wjmyyQ0ZarVIa6zuOsiHWCm9IE9emO+fPk4/hZItMgzOJc8dLLsj7akZI/k0Zfu9BP0O0LQEyh0onsifOLF9px7Z3BHnkEmofUIYzyYxfHLFPUu8yG5ed76IXdo4I/eUYdpULt1QRW/2fdtC3oow+PWb7lzlsQKsltuEevv5JqvjnsDRNZXcTKnCn+fl5lRXw5N1Qts2DwKjXOUj9f3TGEAFJ75T2aNtV4pcOkh5cNB3LCohG07XzXFZ6A0Bn8fAWfVDAk5VOPmpvHaO+l3QwTL7JK5tNTk3/Dy3CwZRHT30IMWzRtoEvgyckD1/RYllerIwlgAK1iN+iJOLFNwKTDiGd+WcX3argvsINwZXPmNtP0qYBr92tg7Q6svVT/EkX3HbASxhFZvXiM9pUX2oLpScCnqBNZDkJ9hg+4Hj4ZlCNfLs4Knz+twDtw6P66aEnMyxrMSK0c3MnZSS0vxTuRCmfko9bQlp7KE/NaVdBxXMmcDnCawjx4DEeUZBudMzL1Sbva2hI="
cache:
  yarn: true
  directories:
    - node_modules
